### PR TITLE
flex: fix compilation error with MSVC 2022

### PR DESCRIPTION
**Pull request by Spudz76**
This appears to fix the MSVC 2022 compilation issue:
```
  C:\src\xmrig\src\crypto\flex\flex.cpp(79,21): error C2131: expression did not evaluate to a constant [C:\src\xmrig\build\cpu\xmrig.vcxproj]
  C:\src\xmrig\src\crypto\flex\flex.cpp(81,20): error C3863: array type 'bool [algoCount]' is not assignable [C:\src\xmrig\build\cpu\xmrig.vcxproj]
```

Also appears to still work on Linux (gcc 12.3.0)

### CODE REVIEW

**Comment by MoneroOcean** [comment]
Thank you. Yes, looks like this will help.
